name: GrimHelper
author: Original Author: RekkuzaRagegjens+-+New Author: Taki21
version: 1.0B1
api: 1.4.0
main: GrimHelper
commands:
 helper:
  usage: /helper
  description: This will send the client whatever message was set in config
